### ISSUE TITLE
Minimal Example.

### ISSUE THREAD

**Issue by sirvon** [viniciusaro/SwiftResolver#3]
Thanks for this lib.

Can you show a minimal example of using this DI?

Like bringing services into a viewModel...

Where put the initial container, in appDelegate?

**Comment by viniciusaro** [comment]
Hi @sirvon! Thanks for the request. I've added some information about how to use the lib in a real project. You can find it in the [wiki](https://github.com/viniciusaro/SwiftResolver/wiki) page.

If you have any suggestions on how to make it clearer let me know.
